[package]
name = "k210-lcd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

k210-hal = { git = "https://github.com/riscv-rust/k210-hal", rev = "fb6c2394" }
riscv = "0.10.1"
